name = "tresses"
description = "Synth library inspired by Mutable Instruments Braids"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]
midi = "~0.2.0"
